---
# Jupyter LLM docker compose by Matthew Printz

version: '3'
services:
  jupyter:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        JULIA_IMAGE: askem-julia-base:build
    ports:
      - "8888:8888"
    # environment:
    #   - DATA_SERVICE_URL=http://data-service:8000
    #   - DEBUG=1
    #   - JUPYTER_SERVER=http://jupyter:8888
    #   - JUPYTER_TOKEN=89f73481102c46c0bc13b2998f9a4fce
    env_file:
      - .env
    command: ["python", "-m", "beaker_kernel.server.dev", "--ip", "0.0.0.0"]
 
  